### ISSUE TITLE
FootprintService.find is not a function

### ISSUE THREAD

**Issue by cesar2064** [trailsjs/trailpack-express#23]
Hi I had the following error when I tried to access the footprint url "/api/v1/user" :

`error:  TypeError: FootprintService.find is not a function
    at FootprintController.find (D:\Proyectos\covead\core\node_modules\trailpack-express\api\controllers\FootprintController.js:44:35)
    at Layer.handle [as handle_request] (D:\Proyectos\covead\core\node_modules\router\lib\layer.js:93:5)
    at next (D:\Proyectos\covead\core\node_modules\router\lib\route.js:138:13)
    at Footprint.find (D:\Proyectos\covead\core\node_modules\trailpack-express\api\policies\FootprintPolicy.js:38:5)
    at Layer.handle [as handle_request] (D:\Proyectos\covead\core\node_modules\router\lib\layer.js:93:5)
    at next (D:\Proyectos\covead\core\node_modules\router\lib\route.js:138:13)
    at Route.dispatch (D:\Proyectos\covead\core\node_modules\router\lib\route.js:109:3)
    at handle (D:\Proyectos\covead\core\node_modules\router\index.js:519:11)
    at Layer.handle [as handle_request] (D:\Proyectos\covead\core\node_modules\router\lib\layer.js:93:5)
    at D:\Proyectos\covead\core\node_modules\router\index.js:290:22
    at param (D:\Proyectos\covead\core\node_modules\router\index.js:367:14)
    at param (D:\Proyectos\covead\core\node_modules\router\index.js:383:14)
    at param (D:\Proyectos\covead\core\node_modules\router\index.js:383:14)
    at Function.process_params (D:\Proyectos\covead\core\node_modules\router\index.js:428:3)
    at next (D:\Proyectos\covead\core\node_modules\router\index.js:284:10)
    at methodOverride (D:\Proyectos\covead\core\node_modules\method-override\index.js:65:14)
    at Layer.handle [as handle_request] (D:\Proyectos\covead\core\node_modules\router\lib\layer.js:93:5)
    at trim_prefix (D:\Proyectos\covead\core\node_modules\router\index.js:329:13)
    at D:\Proyectos\covead\core\node_modules\router\index.js:293:7
    at Function.process_params (D:\Proyectos\covead\core\node_modules\router\index.js:348:12)
    at next (D:\Proyectos\covead\core\node_modules\router\index.js:284:10)
    at compression (D:\Proyectos\covead\core\node_modules\compression\index.js:219:5)`

I am using Knex and pg for the models.

**Comment by jaumard** [comment]
Knex doesn't have a `FootprintService` yet, so footprints actually don't work with knex. See https://github.com/trailsjs/trailpack-knex/blob/master/api/services/FootprintService.js
Please open an issue on the knex repo instead.
Thanks :)

**Comment by cesar2064** [comment]
Ok thanks :D
