### ISSUE TITLE
Trails.js v1 compatibility broken.

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/trailpack-express#52]
@tjwebb @jaumard 
After fresh install of `yo generator-trailpack` and creating new project getting this error:

```
Error: Cannot find module 'trails/controller'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Repos/Coding/OpenSource/FrameworkBenchmarks/frameworks/JavaScript/trailsjs/node_modules/trailpack-express/lib/utils.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Repos/Coding/OpenSource/FrameworkBenchmarks/frameworks/JavaScript/trailsjs/node_modules/trailpack-express/lib/server.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by konstantinzolotarev** [comment]
Not really sure is it correct place for this issue. 
I think it should be moved to `generator` because it's installing version `2.0.0-rc1` for `trailpack-express` and 1st for all other modules.

```
"dependencies": {
    "express": "^5.0.0-alpha.2",
    "trailpack-core": "^1.0.0",
    "trailpack-express": "^2.0.0-rc1",
    "trailpack-repl": "^1.0.8",
    "trailpack-router": "^1.0.2",
    "trails": "^1.0.4",
    "trails-controller": "^1.0.0-beta-2",
    "trails-model": "^1.0.0-beta-2",
    "trails-policy": "^1.0.1",
    "trails-service": "1.0.0-beta-2",
    "winston": "^2.2"
  }
```

**Comment by jaumard** [comment]
Hapi has the same problem before, @tjwebb fix it but don't know how exactly

**Comment by konstantinzolotarev** [comment]
To solve you have to change `"trailpack-express": "^2.0.0-rc1",` to `"trailpack-express": "^1.1.0",`

**Comment by jaumard** [comment]
Is it something fixed now @konstantinzolotarev  ? Should be ok I think

**Comment by jaumard** [comment]
For me it's fix now :)
