### ISSUE TITLE
Bad imports for v3

### ISSUE THREAD

**Issue by jamrizzi** [trailsjs/trailpack-express#64]
```sh
> trailblazer@0.0.0 start /home/jamrizzi/Projects/trailblazer
> node node_modules/babel-cli/bin/babel-node server.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'trails/lib/controller'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jamrizzi/Projects/trailblazer/node_modules/trailpack-express/lib/utils.js:3:20)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jamrizzi/Projects/trailblazer/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jamrizzi/Projects/trailblazer/node_modules/trailpack-express/lib/server.js:14:15)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trailblazer@0.0.0 start: `node node_modules/babel-cli/bin/babel-node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trailblazer@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jamrizzi/.npm/_logs/2018-02-14T20_23_44_482Z-debug.log

```

**Comment by scott-wyatt** [comment]
The `c` in `controller` needs to be capitalized eg. `Controller`.

**Comment by scott-wyatt** [comment]
Lol, just saw in your reference you fixed it, sorry about that @jamrizzi

**Comment by jaumard** [comment]
But it's only for v3 and this trailpack is NOT compatible v3 yet (far from it)

**Comment by jaumard** [comment]
Just to put you up to date V3 branch is waiting for this PR to be merge and deploy -> https://github.com/trailsjs/trails/pull/317
I think it's the minimum requirement before going further on this trailpack for v3 support :(
